[pytest]

# 1. Command-line options
addopts = -s -v --alluredir=reports/allure-results --html=reports/report.html --self-contained-html

# 2. Test discovery paths
testpaths = 
    apps/helixTv/tests
    apps/helixFi/tests

pythonpath = .

# 3. Registration of custom markers
markers =
    smoke: vital tests for basic functionality
    regression: full suite of tests
    login: tests specifically for authentication
    helixTv: tests related to the Helix TV app
    helixFi: tests related to the Helix Fi app

# 4. Logging configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
